namespace Domain.Enums
{
    public enum ProvinciasEnum
    {
        AZUA = 1,
		BAHORUCO,
		BARAHONA,
		DAJABON,
		DISTRITO_NACIONAL,
		DUARTE,
		EL_SEYBO,
		ELIAS_PIÑA,
		ESPAILLAT,
		HATO_MAYOR,
		HERMANAS_MIRABAL_o_Salcedo,
		INDEPENDENCIA,
		LA_ALTAGRACIA,
		LA_ROMANA,
		LA_VEGA,
		MARIA_TRINIDAD_SANCHEZ,
		MONSEÑOR_NOUEL,
		MONTE_PLATA,
		MONTECRISTI,
		PEDERNALES,
		PERAVIA,
		PUERTO_PLATA,
		SAMANA,
		SAN_CRISTOBAL,
		SAN_JOSE_DE_OCOA,
		SAN_JUAN,
		SAN_PEDRO_DE_MACORIS,
		SANCHEZ_RAMIREZ,
		SANTIAGO,
		SANTIAGO_RODRIGUEZ,
		SANTO_DOMINGO,
		VALVERDE
    }
}